# Generated by Django 2.2.1 on 2019-06-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('chinese_name', models.CharField(max_length=200)),
                ('original_name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('publish_date', models.DateField(verbose_name='Published date')),
                ('binding_type', models.CharField(max_length=20)),
                ('paper_type', models.CharField(max_length=20)),
                ('pages', models.IntegerField()),
                ('book_count', models.IntegerField()),
                ('language', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('purchase_date', models.DateField(verbose_name='Purchased date')),
                ('thumb_image', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_book_count', models.IntegerField()),
                ('total_set_count', models.IntegerField()),
            ],
        ),
    ]
