# Generated by Django 2.2.1 on 2019-06-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.Bookshelf'),
        ),
    ]
