# Generated by Django 2.2.1 on 2019-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0005_auto_20190607_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('chinese_name', models.CharField(blank=True, max_length=200)),
                ('nation', models.CharField(choices=[('CHINA', '中国'), ('BRITAIN', '英国'), ('FRANCE', '法国'), ('AMERICA', '美国'), ('RUSSIA', '俄国'), ('JAPAN', '日本'), ('IRELAND', '爱尔兰'), ('AUSTRALIA', '澳大利亚'), ('ISRAEL', '以色列')], max_length=100)),
                ('dynasty', models.CharField(blank=True, choices=[('XIA', '夏'), ('SHANG', '商'), ('WESTZHOU', '西周'), ('EASTZHOU', '东周'), ('CHUNQIU', '春秋'), ('ZHANGUO', '战国'), ('QIN', '秦'), ('WESTHAN', '西汉'), ('EASTHAN', '东汉'), ('WEI', '魏'), ('SHU', '蜀'), ('WU', '吴'), ('WESTJIN', '西晋'), ('EASTJIN', '东晋'), ('NANBEICHAO', '南北朝'), ('SUI', '隋'), ('TANG', '唐'), ('WUDAI', '五代十国'), ('NORTHSONG', '北宋'), ('SOUTHSONG', '南宋'), ('YUAN', '元'), ('MING', '明'), ('QING', '清')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='chinese_name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
