# Generated by Django 2.2.1 on 2019-06-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0006_auto_20190610_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dynasty',
            field=models.CharField(blank=True, choices=[('XIA', '夏'), ('SHANG', '商'), ('WESTZHOU', '西周'), ('EASTZHOU', '东周'), ('CHUNQIU', '春秋'), ('ZHANGUO', '战国'), ('QIN', '秦'), ('WESTHAN', '西汉'), ('EASTHAN', '东汉'), ('WEI', '魏'), ('SHU', '蜀'), ('WU', '吴'), ('WESTJIN', '西晋'), ('EASTJIN', '东晋'), ('NANBEICHAO', '南北朝'), ('SUI', '隋'), ('TANG', '唐'), ('WUDAI', '五代十国'), ('NORTHSONG', '北宋'), ('SOUTHSONG', '南宋'), ('YUAN', '元'), ('MING', '明'), ('QING', '清'), ('MINGUO', '民国'), ('DANGDAI', '当代')], max_length=100),
        ),
    ]
