# Generated by Django 2.2.1 on 2019-06-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0012_auto_20190610_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding_type',
            field=models.CharField(choices=[('HARDCOVER', '精装'), ('PAPERCOVER', '平装'), ('BOXSET', '盒装'), ('WIREBOUND', '线装')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('CHINESE', '中文'), ('ENGLISH', '英文'), ('CHINESE/ENGLISH', '中文/英文'), ('JANPANESE', '日文')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('COATEDPAPER', '铜版纸'), ('OFFSETPAPER', '胶版纸'), ('CHINAPAPER', '宣纸'), ('MUNKENPAPER', '轻型纸'), ('PUREQUALITYPAPER', '纯质纸'), ('WRITINGPAPER', '书写纸'), ('ELEGANTPAPER', '雅致纸')], default=None, max_length=20),
        ),
    ]
