# Generated by Django 2.2.1 on 2019-06-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0014_auto_20190610_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
