# Generated by Django 2.2.1 on 2019-06-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0015_bookshelf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
