# Generated by Django 2.2.1 on 2019-06-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0016_book_translator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='翻译/编纂/整理'),
        ),
    ]
