# Generated by Django 2.2.1 on 2019-06-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0017_auto_20190610_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding_type',
            field=models.CharField(choices=[('HARDCOVER', '精装'), ('PAPERCOVER', '平装'), ('BOXSET', '盒装'), ('WIREBOUND', '线装')], max_length=20, verbose_name='装帧'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_count',
            field=models.IntegerField(verbose_name='套装数量'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.Bookshelf', verbose_name='所在书架'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(max_length=30, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('CHINESE', '中文'), ('ENGLISH', '英文'), ('CHINESE/ENGLISH', '中文/英文'), ('JANPANESE', '日文')], max_length=30, verbose_name='正文语种'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(verbose_name='页数'),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('COATEDPAPER', '铜版纸'), ('OFFSETPAPER', '胶版纸'), ('CHINAPAPER', '宣纸'), ('MUNKENPAPER', '轻型纸'), ('PUREQUALITYPAPER', '纯质纸'), ('WRITINGPAPER', '书写纸'), ('ELEGANTPAPER', '雅致纸')], default=None, max_length=20, verbose_name='用纸'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.FloatField(verbose_name='定价'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='purchase_date',
            field=models.DateField(verbose_name='购入日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='purchase_price',
            field=models.FloatField(verbose_name='购入价格'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumb_image',
            field=models.ImageField(upload_to='image/', verbose_name='缩略图'),
        ),
    ]
