# Generated by Django 2.2.1 on 2019-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0019_auto_20190610_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='商品链接'),
        ),
    ]
