# Generated by Django 2.2.1 on 2019-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0020_auto_20190610_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='binding_type',
            field=models.CharField(choices=[('精装', '精装'), ('PAPERCOVER', '平装'), ('BOXSET', '盒装'), ('WIREBOUND', '线装')], max_length=20, verbose_name='装帧'),
        ),
    ]
