# Generated by Django 2.2.2 on 2019-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0023_auto_20190610_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('中文', '中文'), ('英文', '英文'), ('中文/英文', '中文/英文'), ('日文', '日文')], max_length=30, verbose_name='正文语种'),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('铜版纸', '铜版纸'), ('胶版纸', '胶版纸'), ('宣纸', '宣纸'), ('轻型纸', '轻型纸'), ('纯质纸', '纯质纸'), ('书写纸', '书写纸'), ('雅致纸', '雅致纸')], default=None, max_length=20, verbose_name='用纸'),
        ),
    ]
