# Generated by Django 2.2.2 on 2019-06-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0026_auto_20190611_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
