# Generated by Django 2.2.2 on 2019-06-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0034_auto_20190612_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['nation', 'dynasty', 'name', 'chinese_name']},
        ),
    ]
