# Generated by Django 2.2.2 on 2019-06-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0039_auto_20190613_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('铜版纸', '铜版纸'), ('胶版纸', '胶版纸'), ('宣纸', '宣纸'), ('轻型纸', '轻型纸'), ('纯质纸', '纯质纸'), ('书写纸', '书写纸'), ('雅致纸', '雅致纸'), ('特种纸', '特种纸')], default=None, max_length=20, verbose_name='用纸'),
        ),
    ]
