# Generated by Django 2.2.2 on 2019-06-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0040_auto_20190616_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['nation', 'dynasty', 'chinese_name', 'name']},
        ),
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('中', '中'), ('德', '德'), ('英', '英'), ('法', '法'), ('美', '美'), ('俄', '俄'), ('日', '日'), ('加', '加'), ('爱尔兰', '爱尔兰'), ('澳', '澳'), ('以色列', '以色列'), ('瑞士', '瑞士'), ('阿根廷', '阿根廷'), ('哥伦比亚', '哥伦比亚'), ('奥地利', '奥地利'), ('西班牙', '西班牙')], max_length=100),
        ),
    ]
