# Generated by Django 2.2.2 on 2019-06-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0041_auto_20190617_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('中', '中'), ('德', '德'), ('英', '英'), ('法', '法'), ('美', '美'), ('俄', '俄'), ('日', '日'), ('加', '加'), ('爱尔兰', '爱尔兰'), ('澳', '澳'), ('以色列', '以色列'), ('瑞士', '瑞士'), ('阿根廷', '阿根廷'), ('哥伦比亚', '哥伦比亚'), ('奥地利', '奥地利'), ('西班牙', '西班牙'), ('挪威', '挪威')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='binding_type',
            field=models.CharField(choices=[('精装', '精装'), ('平装', '平装'), ('盒装', '盒装'), ('线装', '线装')], default='精装', max_length=20, verbose_name='装帧'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_count',
            field=models.IntegerField(default=1, verbose_name='套装数量'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('中文', '中文'), ('英文', '英文'), ('中文/英文', '中文/英文'), ('日文', '日文')], default='中文', max_length=30, verbose_name='正文语种'),
        ),
        migrations.AlterField(
            model_name='book',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('铜版纸', '铜版纸'), ('胶版纸', '胶版纸'), ('宣纸', '宣纸'), ('轻型纸', '轻型纸'), ('纯质纸', '纯质纸'), ('书写纸', '书写纸'), ('雅致纸', '雅致纸'), ('特种纸', '特种纸')], default='胶版纸', max_length=20, verbose_name='用纸'),
        ),
    ]
