# Generated by Django 2.2.2 on 2019-06-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0042_auto_20190622_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['purchase_date']},
        ),
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('中国', '中国'), ('德国', '德国'), ('英国', '英国'), ('法国', '法国'), ('美国', '美国'), ('俄罗斯', '俄罗斯'), ('日本', '日本'), ('加拿大', '加拿大'), ('前苏联', '前苏联'), ('爱尔兰', '爱尔兰'), ('澳大利亚', '澳大利亚'), ('以色列', '以色列'), ('瑞士', '瑞士'), ('阿根廷', '阿根廷'), ('哥伦比亚', '哥伦比亚'), ('奥地利', '奥地利'), ('西班牙', '西班牙'), ('挪威', '挪威'), ('瑞典', '瑞典'), ('意大利', '意大利')], max_length=100),
        ),
    ]
