# Generated by Django 2.2.2 on 2019-12-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0047_auto_20191223_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id']},
        ),
    ]
