# Generated by Django 2.2.2 on 2020-02-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0049_author_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='intro',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
