# Generated by Django 2.2.2 on 2020-02-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0050_auto_20200207_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='author',
            name='dynasty',
            field=models.CharField(blank=True, choices=[('夏', '夏'), ('商', '商'), ('西周', '西周'), ('东周', '东周'), ('春秋', '春秋'), ('战国', '战国'), ('秦', '秦'), ('西汉', '西汉'), ('东汉', '东汉'), ('魏', '魏'), ('蜀', '蜀'), ('吴', '吴'), ('西晋', '西晋'), ('东晋', '东晋'), ('南北朝', '南北朝'), ('隋', '隋'), ('唐', '唐'), ('五代', '五代'), ('北宋', '北宋'), ('南宁', '南宋'), ('元', '元'), ('明', '明'), ('清', '清'), ('民国', '民国'), ('现代', '现代'), ('当代', '当代')], max_length=100, verbose_name='朝代'),
        ),
        migrations.AlterField(
            model_name='author',
            name='intro',
            field=models.TextField(blank=True, max_length=1500, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('中国', '中国'), ('德国', '德国'), ('英国', '英国'), ('法国', '法国'), ('美国', '美国'), ('俄罗斯', '俄罗斯'), ('日本', '日本'), ('加拿大', '加拿大'), ('前苏联', '前苏联'), ('爱尔兰', '爱尔兰'), ('澳大利亚', '澳大利亚'), ('以色列', '以色列'), ('瑞士', '瑞士'), ('阿根廷', '阿根廷'), ('哥伦比亚', '哥伦比亚'), ('奥地利', '奥地利'), ('西班牙', '西班牙'), ('挪威', '挪威'), ('瑞典', '瑞典'), ('意大利', '意大利')], max_length=100, verbose_name='国籍'),
        ),
    ]
