# Generated by Django 2.2.2 on 2020-02-07 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0052_author_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id', 'nation', 'dynasty', 'chinese_name', 'name']},
        ),
    ]
