# Generated by Django 2.2.2 on 2020-02-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0053_auto_20200207_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumb_image',
            field=models.ImageField(upload_to='image/books/', verbose_name='缩略图'),
        ),
    ]
