# Generated by Django 2.2.2 on 2020-02-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0054_auto_20200207_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['id']},
        ),
    ]
