# Generated by Django 2.2.2 on 2020-02-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0055_auto_20200207_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='introduction',
            field=models.CharField(blank=True, default=None, max_length=1500, null=True, verbose_name='简介'),
        ),
    ]
