# Generated by Django 2.2.3 on 2020-03-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0057_auto_20200210_1214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['nation', 'dynasty', 'chinese_name']},
        ),
    ]
