# Generated by Django 2.2.3 on 2020-05-10 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0058_auto_20200308_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('中国', '中国'), ('德国', '德国'), ('英国', '英国'), ('法国', '法国'), ('美国', '美国'), ('俄罗斯', '俄罗斯'), ('日本', '日本'), ('加拿大', '加拿大'), ('前苏联', '前苏联'), ('爱尔兰', '爱尔兰'), ('澳大利亚', '澳大利亚'), ('以色列', '以色列'), ('瑞士', '瑞士'), ('阿根廷', '阿根廷'), ('哥伦比亚', '哥伦比亚'), ('奥地利', '奥地利'), ('西班牙', '西班牙'), ('挪威', '挪威'), ('瑞典', '瑞典'), ('意大利', '意大利'), ('希腊', '希腊'), ('比利时', '比利时')], max_length=100, verbose_name='国籍'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='bookshelf.Publisher', verbose_name='出版社'),
        ),
    ]
