# Generated by Django 2.2.3 on 2020-05-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0059_auto_20200510_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
