# Generated by Django 2.2.3 on 2020-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0060_auto_20200510_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='introduction',
            field=models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='名称'),
        ),
    ]
