# Generated by Django 2.2.3 on 2020-05-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0062_auto_20200511_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={},
        ),
    ]
