# Generated by Django 2.2.3 on 2020-05-11 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0064_remove_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='bookshelf.Publisher', verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publisher2', to='bookshelf.Publisher', verbose_name='出版社'),
        ),
    ]
