# Generated by Django 2.2.3 on 2020-05-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0065_auto_20200511_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publisher2',
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='bookshelf.Publisher', verbose_name='出版社'),
        ),
    ]
