# Generated by Django 2.2.3 on 2020-05-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0066_auto_20200511_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='名称')),
                ('introduction', models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='简介')),
                ('books', models.ManyToManyField(to='bookshelf.Book')),
            ],
        ),
    ]
