# Generated by Django 2.2.2 on 2020-06-01 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0068_auto_20200513_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['chinese_name']},
        ),
    ]
