# Generated by Django 2.2.2 on 2020-07-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0069_auto_20200601_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='my_comments',
            field=models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='我的点评'),
        ),
        migrations.AddField(
            model_name='book',
            name='my_score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True, verbose_name='我的评分'),
        ),
    ]
