# Generated by Django 2.2.2 on 2020-07-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0070_auto_20200709_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='my_score',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=None, null=True, verbose_name='我的评分'),
        ),
    ]
