# Generated by Django 2.2.2 on 2020-07-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0071_auto_20200709_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='bookshelf.Author'),
        ),
    ]
