# Generated by Django 2.2.2 on 2020-07-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0072_book_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_2nd',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_3rd',
        ),
    ]
