# Generated by Django 2.2.2 on 2020-11-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0073_auto_20200716_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chinese_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='中文译名'),
        ),
    ]
