# Generated by Django 3.1.4 on 2020-12-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0078_auto_20201206_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='registered',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, verbose_name='晒书房登记'),
        ),
    ]
