# Generated by Django 3.1.4 on 2022-04-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0083_auto_20210531_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='bookshelf.Author'),
        ),
    ]
