# Generated by Django 3.2 on 2022-07-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0087_auto_20220709_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='商品链接'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumb_image',
            field=models.ImageField(null=True, upload_to='image/books/', verbose_name='缩略图'),
        ),
    ]
