# Generated by Django 3.2 on 2022-08-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0096_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='douban_score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='豆瓣评分'),
        ),
    ]
