# Generated by Django 3.2 on 2022-09-03 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0100_alter_book_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookseries',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='book_series',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshelf.bookseries', verbose_name='丛书'),
        ),
    ]
