# Generated by Django 3.1.6 on 2022-09-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0103_auto_20220906_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
