# Generated by Django 3.1.6 on 2022-09-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0104_bookshelf_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='total_book_count',
        ),
        migrations.RemoveField(
            model_name='bookshelf',
            name='total_set_count',
        ),
    ]
