# Generated by Django 4.1.3 on 2022-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0110_alter_book_language_alter_taggeditem_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='compose_type',
            field=models.CharField(choices=[('横排', '横排'), ('竖排', '竖排')], default='横排', max_length=10, verbose_name='排版'),
        ),
    ]
