# Generated by Django 4.1.3 on 2022-11-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0114_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumb_image',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='缩略图'),
        ),
    ]
