# Generated by Django 4.1.3 on 2023-02-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0115_alter_book_thumb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, unique=True, verbose_name='名称')),
                ('introduction', models.TextField(blank=True, default=None, max_length=1500, null=True, verbose_name='简介')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('未知', '未知'), ('中国', '中国'), ('德国', '德国'), ('英国', '英国'), ('法国', '法国'), ('美国', '美国'), ('俄罗斯', '俄罗斯'), ('日本', '日本'), ('加拿大', '加拿大'), ('前苏联', '前苏联'), ('爱尔兰', '爱尔兰'), ('澳大利亚', '澳大利亚'), ('以色列', '以色列'), ('瑞士', '瑞士'), ('阿根廷', '阿根廷'), ('哥伦比亚', '哥伦比亚'), ('奥地利', '奥地利'), ('西班牙', '西班牙'), ('挪威', '挪威'), ('瑞典', '瑞典'), ('意大利', '意大利'), ('希腊', '希腊'), ('比利时', '比利时'), ('墨西哥', '墨西哥'), ('荷兰', '荷兰'), ('巴西', '巴西'), ('波兰', '波兰'), ('伊朗', '伊朗'), ('古巴', '古巴'), ('波斯', '波斯'), ('智利', '智利'), ('南非', '南非'), ('马来西亚', '马来西亚'), ('捷克', '捷克'), ('毛里求斯', '毛里求斯'), ('丹麦', '丹麦')], max_length=100, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumb_image',
            field=models.ImageField(blank=True, default=None, upload_to='image/books/', verbose_name='缩略图'),
        ),
    ]
