# Generated by Django 4.1.3 on 2023-02-23 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0116_brand_alter_author_nation_alter_book_thumb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshelf.brand', verbose_name='品牌'),
        ),
    ]
